name: deploiement-dockerhub-main

on:
  push:
    branches:
      - main  

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        # voir : https://github.com/marketplace/actions/build-and-push-docker-images#customizing
        with:
          context: "{{defaultContext}}" # Répertoire de contexte (racine du repo par défaut)
          file: ./Dockerfile  # Chemin vers le Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/backend:latest